version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - REACT_APP_SEARCH_LOCATIONS_URL=http://localhost:5000/events
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"